[package]
name = "pda-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonrpsee = { version = "0.24", features = ["macros", "server", "http-client"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
celestia-types = "0.11"
