services:
  celestia-node:
    image: ${CELESTIA_DOCKER_IMAGE}
    container_name: ${CELESTIA_NODE_NAME}
    command: celestia ${CELESTIA_NODE_TYPE} start --core.ip ${CELESTIA_NODE_CORE_IP}
    volumes:
      - ${CELESTIA_DATA_DIR}:/home/celestia
    expose:
      - "${CELESTIA_P2P_PORT}"
      - "${CELESTIA_RPC_PORT}"
    networks:
      - internal
    restart: unless-stopped
    env_file:
      - /app/.env

  pda-proxy:
    image: pda-proxy
    # build: .  # OPTIONAL: for local development
    depends_on:
      - celestia-node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./service/static:/app/static  # OPTIONAL: for local development
      - ${PDA_DB_PATH}:${PDA_DB_PATH}
      - /etc/letsencrypt/live/${TLS_DOMAIN}/fullchain.pem:/etc/letsencrypt/live/${TLS_DOMAIN}/fullchain.pem
      - /etc/letsencrypt/live/${TLS_DOMAIN}/privkey.pem:/etc/letsencrypt/live/${TLS_DOMAIN}/privkey.pem
    environment:
      # NOTE: Overrides any .env settings
      - TLS_CERTS_PATH=/etc/letsencrypt/live/${TLS_DOMAIN}/fullchain.pem
      - TLS_KEY_PATH=/etc/letsencrypt/live/${TLS_DOMAIN}/privkey.pem
      - RUST_LOG=pda_proxy=debug
    env_file:
      - /app/.env
    networks:
      - internal
    ports:
      - "443:${PDA_PORT}"  # Public HTTPS
    restart: unless-stopped

networks:
  internal:
    driver: bridge
    internal: true
